//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LittleBooks.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AdminResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdminResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LittleBooks.Common.Resources.AdminResources", typeof(AdminResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პროექტის შესახებ.
        /// </summary>
        public static string aboutProject {
            get {
                return ResourceManager.GetString("aboutProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ავტორის დამატება.
        /// </summary>
        public static string addAuthor {
            get {
                return ResourceManager.GetString("addAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მოთხრობის დამატება.
        /// </summary>
        public static string addTale {
            get {
                return ResourceManager.GetString("addTale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ავტორი.
        /// </summary>
        public static string author {
            get {
                return ResourceManager.GetString("author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ავტორები.
        /// </summary>
        public static string authors {
            get {
                return ResourceManager.GetString("authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to უკან.
        /// </summary>
        public static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to კონტაქტი.
        /// </summary>
        public static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to შექმნა.
        /// </summary>
        public static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ახლის დამატება.
        /// </summary>
        public static string createNew {
            get {
                return ResourceManager.GetString("createNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to წაშლა.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to რედაქტირება.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პროექტის შესახებ რედაქტირება.
        /// </summary>
        public static string editAboutProject {
            get {
                return ResourceManager.GetString("editAboutProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ავტორის რედაქტირება.
        /// </summary>
        public static string editAuthor {
            get {
                return ResourceManager.GetString("editAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to კონტაქტის რედაქტირება.
        /// </summary>
        public static string editContact {
            get {
                return ResourceManager.GetString("editContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მოთხრობის რედაქტირება.
        /// </summary>
        public static string editTale {
            get {
                return ResourceManager.GetString("editTale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to სურათი.
        /// </summary>
        public static string image {
            get {
                return ResourceManager.GetString("image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to დამახსოვრება.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to აირჩიეთ.
        /// </summary>
        public static string select {
            get {
                return ResourceManager.GetString("select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მოთხრობები.
        /// </summary>
        public static string Tales {
            get {
                return ResourceManager.GetString("Tales", resourceCulture);
            }
        }
    }
}
