//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LittleBooks.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tale
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string TaleLink { get; set; }
        public Nullable<int> AuthorId { get; set; }
        public string ImageUrl { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
    
        public virtual Author Author { get; set; }
    }
}
